#!/usr/bin/env python3
"""Audit the SotDL shop-generator research data.

Run from the repository root:
    python scripts/audit-shop-data.py

The script reads the item catalogue, spell catalogues, and coverage manifest,
then writes research/shop-generator/coverage-report.md. By default it reports
structural problems without failing CI while the imported spell catalogue is
being cleaned. Set AUDIT_STRICT=1 to return a non-zero status for structural
errors.
"""

from __future__ import annotations

import csv
from collections import Counter, defaultdict
import os
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "research" / "shop-generator"
ITEMS = DATA / "items.csv"
MANIFEST = DATA / "coverage-manifest.csv"
REPORT = DATA / "coverage-report.md"
SPELL_FILES = sorted(DATA.glob("spells-*.csv"))


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def clean(value: str | None) -> str:
    return (value or "").strip()


def main() -> int:
    errors: list[str] = []
    warnings: list[str] = []

    items = read_csv(ITEMS)
    manifest = read_csv(MANIFEST)

    item_ids = [clean(row.get("id")) for row in items]
    duplicate_item_ids = sorted(k for k, n in Counter(item_ids).items() if k and n > 1)
    if duplicate_item_ids:
        errors.append("Duplicate item IDs: " + ", ".join(duplicate_item_ids))

    item_names = [clean(row.get("name")).casefold() for row in items]
    duplicate_item_names = sorted(k for k, n in Counter(item_names).items() if k and n > 1)
    if duplicate_item_names:
        warnings.append("Duplicate item names: " + ", ".join(duplicate_item_names))

    required_item_fields = ("id", "name", "category", "price", "availability", "source", "page")
    for index, row in enumerate(items, start=2):
        missing = [field for field in required_item_fields if not clean(row.get(field))]
        if missing:
            errors.append(f"items.csv row {index} missing: {', '.join(missing)}")

    known_ids = set(item_ids)
    broken_manifest_refs: list[str] = []
    for row in manifest:
        refs = [part.strip() for part in clean(row.get("dataset_id")).split("|") if part.strip()]
        for ref in refs:
            if ref not in known_ids:
                broken_manifest_refs.append(f"{row.get('name')} -> {ref}")
    if broken_manifest_refs:
        errors.append("Broken coverage-manifest dataset references: " + "; ".join(broken_manifest_refs))

    spell_rows: list[dict[str, str]] = []
    spell_counts_by_file: dict[str, int] = {}
    for path in SPELL_FILES:
        rows = read_csv(path)
        spell_counts_by_file[path.name] = len(rows)
        for row in rows:
            row["_file"] = path.name
            spell_rows.append(row)

    spell_keys: list[tuple[str, str, str]] = []
    malformed_spells: list[str] = []
    for index, row in enumerate(spell_rows, start=2):
        name = clean(row.get("name") or row.get("spell"))
        rank = clean(row.get("rank"))
        tradition = clean(row.get("tradition"))
        source = clean(row.get("source"))
        page = clean(row.get("page"))
        if not name or not rank or not tradition:
            malformed_spells.append(f"{row['_file']} row {index}: missing name/rank/tradition")
        if rank and not rank.isdigit():
            malformed_spells.append(f"{row['_file']} row {index}: non-numeric rank {rank!r}")
        if not source or not page:
            warnings.append(f"{row['_file']} row {index}: missing source or page for {name or '(unnamed)'}")
        spell_keys.append((name.casefold(), rank, tradition.casefold()))

    duplicate_spells = sorted(k for k, n in Counter(spell_keys).items() if k[0] and n > 1)
    if malformed_spells:
        errors.extend(malformed_spells)

    statuses = Counter(clean(row.get("status")) for row in manifest)
    by_source: dict[str, Counter[str]] = defaultdict(Counter)
    for row in manifest:
        by_source[clean(row.get("source"))][clean(row.get("status"))] += 1

    missing_review = [row for row in manifest if clean(row.get("status")) == "missing-review"]
    missing_special = [row for row in manifest if clean(row.get("status")) == "missing-special"]
    missing_generator = [row for row in manifest if clean(row.get("status")) == "missing-generator"]
    excluded = [row for row in manifest if clean(row.get("status")).startswith("excluded")]

    lines: list[str] = [
        "# Shop Generator Coverage Report",
        "",
        "> Generated by `python scripts/audit-shop-data.py`. Do not edit this report manually.",
        "",
        "## Summary",
        "",
        f"- Fixed-price catalogue rows: **{len(items)}**",
        f"- Spell catalogue rows: **{len(spell_rows)}** across **{len(SPELL_FILES)}** files",
        f"- Coverage manifest rows: **{len(manifest)}**",
        f"- Entries requiring an inclusion decision: **{len(missing_review)}**",
        f"- Special-stock records not yet implemented: **{len(missing_special)}**",
        f"- Generator systems not yet implemented: **{len(missing_generator)}**",
        f"- Deliberate exclusions: **{len(excluded)}**",
        "",
        "## Manifest status",
        "",
        "| Status | Count |",
        "|---|---:|",
    ]
    for status, count in sorted(statuses.items()):
        lines.append(f"| {status or '(blank)'} | {count} |")

    lines.extend(["", "## Source coverage", "", "| Source | Status breakdown |", "|---|---|"])
    for source, counts in sorted(by_source.items()):
        breakdown = ", ".join(f"{status}: {count}" for status, count in sorted(counts.items()))
        lines.append(f"| {source} | {breakdown} |")

    lines.extend(["", "## Inclusion decisions still required", ""])
    if missing_review:
        for row in missing_review:
            lines.append(f"- **{row['name']}** — {row['source']} p. {row['page']}: {row['notes']}")
    else:
        lines.append("None.")

    lines.extend(["", "## Special stock not yet implemented", ""])
    if missing_special:
        for row in missing_special:
            lines.append(f"- **{row['name']}** — {row['source']} p. {row['page']}: {row['notes']}")
    else:
        lines.append("None.")

    lines.extend(["", "## Generator systems not yet implemented", ""])
    if missing_generator:
        for row in missing_generator:
            lines.append(f"- **{row['name']}** — {row['source']} pp. {row['page']}: {row['notes']}")
    else:
        lines.append("None.")

    lines.extend(["", "## Spell files", "", "| File | Rows |", "|---|---:|"])
    for filename, count in sorted(spell_counts_by_file.items()):
        lines.append(f"| `{filename}` | {count} |")

    lines.extend(["", "## Data-quality findings", ""])
    if duplicate_item_ids:
        lines.append("- Duplicate item IDs: " + ", ".join(duplicate_item_ids))
    else:
        lines.append("- No duplicate item IDs.")
    if duplicate_item_names:
        lines.append("- Duplicate item names: " + ", ".join(duplicate_item_names))
    else:
        lines.append("- No duplicate item names.")
    if duplicate_spells:
        lines.append(f"- Duplicate spell keys requiring review: **{len(duplicate_spells)}**")
        for name, rank, tradition in duplicate_spells[:50]:
            lines.append(f"  - {name} — rank {rank}, {tradition}")
        if len(duplicate_spells) > 50:
            lines.append(f"  - …and {len(duplicate_spells) - 50} more")
    else:
        lines.append("- No duplicate spell keys.")

    if warnings:
        lines.extend(["", "## Warnings", ""])
        lines.extend(f"- {warning}" for warning in warnings[:100])
        if len(warnings) > 100:
            lines.append(f"- …and {len(warnings) - 100} more")

    if errors:
        lines.extend(["", "## Structural errors", ""])
        lines.extend(f"- {error}" for error in errors[:100])
        if len(errors) > 100:
            lines.append(f"- …and {len(errors) - 100} more")
    else:
        lines.extend(["", "## Structural errors", "", "None."])

    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {REPORT.relative_to(ROOT)}")
    print(f"Items: {len(items)} | Spells: {len(spell_rows)} | Manifest: {len(manifest)}")
    if errors:
        print(f"Audit found {len(errors)} structural error(s).", file=sys.stderr)
        if os.environ.get("AUDIT_STRICT") == "1":
            return 1
        print("Report-only mode: CI remains green. Set AUDIT_STRICT=1 to fail on these errors.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
